/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as OrdersOrderNumberRouteImport } from './routes/orders.$orderNumber'
import { Route as DashboardWithdrawalsRouteImport } from './routes/dashboard.withdrawals'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardLinksRouteImport } from './routes/dashboard.links'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiCheckoutRouteImport } from './routes/api.checkout'
import { Route as ApiShippingDestinationsRouteImport } from './routes/api.shipping.destinations'
import { Route as ApiShippingCostsRouteImport } from './routes/api.shipping.costs'
import { Route as ApiPakasirWebhookRouteImport } from './routes/api.pakasir.webhook'
import { Route as ApiOgSlugRouteImport } from './routes/api.og.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const OrdersOrderNumberRoute = OrdersOrderNumberRouteImport.update({
  id: '/orders/$orderNumber',
  path: '/orders/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawalsRoute = DashboardWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinksRoute = DashboardLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingDestinationsRoute = ApiShippingDestinationsRouteImport.update({
  id: '/api/shipping/destinations',
  path: '/api/shipping/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingCostsRoute = ApiShippingCostsRouteImport.update({
  id: '/api/shipping/costs',
  path: '/api/shipping/costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPakasirWebhookRoute = ApiPakasirWebhookRouteImport.update({
  id: '/api/pakasir/webhook',
  path: '/api/pakasir/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSlugRoute = ApiOgSlugRouteImport.update({
  id: '/api/og/$slug',
  path: '/api/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/pakasir/webhook': typeof ApiPakasirWebhookRoute
  '/api/shipping/costs': typeof ApiShippingCostsRoute
  '/api/shipping/destinations': typeof ApiShippingDestinationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/pakasir/webhook': typeof ApiPakasirWebhookRoute
  '/api/shipping/costs': typeof ApiShippingCostsRoute
  '/api/shipping/destinations': typeof ApiShippingDestinationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/health': typeof ApiHealthRoute
  '/dashboard/links': typeof DashboardLinksRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/withdrawals': typeof DashboardWithdrawalsRoute
  '/orders/$orderNumber': typeof OrdersOrderNumberRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/og/$slug': typeof ApiOgSlugRoute
  '/api/pakasir/webhook': typeof ApiPakasirWebhookRoute
  '/api/shipping/costs': typeof ApiShippingCostsRoute
  '/api/shipping/destinations': typeof ApiShippingDestinationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/dashboard/links'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/withdrawals'
    | '/orders/$orderNumber'
    | '/dashboard/'
    | '/api/og/$slug'
    | '/api/pakasir/webhook'
    | '/api/shipping/costs'
    | '/api/shipping/destinations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/onboarding'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/dashboard/links'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/withdrawals'
    | '/orders/$orderNumber'
    | '/dashboard'
    | '/api/og/$slug'
    | '/api/pakasir/webhook'
    | '/api/shipping/costs'
    | '/api/shipping/destinations'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/auth'
    | '/dashboard'
    | '/onboarding'
    | '/sitemap.xml'
    | '/api/checkout'
    | '/api/health'
    | '/dashboard/links'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/settings'
    | '/dashboard/withdrawals'
    | '/orders/$orderNumber'
    | '/dashboard/'
    | '/api/og/$slug'
    | '/api/pakasir/webhook'
    | '/api/shipping/costs'
    | '/api/shipping/destinations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiHealthRoute: typeof ApiHealthRoute
  OrdersOrderNumberRoute: typeof OrdersOrderNumberRoute
  ApiOgSlugRoute: typeof ApiOgSlugRoute
  ApiPakasirWebhookRoute: typeof ApiPakasirWebhookRoute
  ApiShippingCostsRoute: typeof ApiShippingCostsRoute
  ApiShippingDestinationsRoute: typeof ApiShippingDestinationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/orders/$orderNumber': {
      id: '/orders/$orderNumber'
      path: '/orders/$orderNumber'
      fullPath: '/orders/$orderNumber'
      preLoaderRoute: typeof OrdersOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/withdrawals': {
      id: '/dashboard/withdrawals'
      path: '/withdrawals'
      fullPath: '/dashboard/withdrawals'
      preLoaderRoute: typeof DashboardWithdrawalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/links': {
      id: '/dashboard/links'
      path: '/links'
      fullPath: '/dashboard/links'
      preLoaderRoute: typeof DashboardLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping/destinations': {
      id: '/api/shipping/destinations'
      path: '/api/shipping/destinations'
      fullPath: '/api/shipping/destinations'
      preLoaderRoute: typeof ApiShippingDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping/costs': {
      id: '/api/shipping/costs'
      path: '/api/shipping/costs'
      fullPath: '/api/shipping/costs'
      preLoaderRoute: typeof ApiShippingCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pakasir/webhook': {
      id: '/api/pakasir/webhook'
      path: '/api/pakasir/webhook'
      fullPath: '/api/pakasir/webhook'
      preLoaderRoute: typeof ApiPakasirWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$slug': {
      id: '/api/og/$slug'
      path: '/api/og/$slug'
      fullPath: '/api/og/$slug'
      preLoaderRoute: typeof ApiOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardLinksRoute: typeof DashboardLinksRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWithdrawalsRoute: typeof DashboardWithdrawalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLinksRoute: DashboardLinksRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWithdrawalsRoute: DashboardWithdrawalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiHealthRoute: ApiHealthRoute,
  OrdersOrderNumberRoute: OrdersOrderNumberRoute,
  ApiOgSlugRoute: ApiOgSlugRoute,
  ApiPakasirWebhookRoute: ApiPakasirWebhookRoute,
  ApiShippingCostsRoute: ApiShippingCostsRoute,
  ApiShippingDestinationsRoute: ApiShippingDestinationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
